all: risk_spi risk_spi_cards risk_spi_gamestate risk_spi_stats

risk_spi: risk_spi.c
	gcc risk_spi.c -o risk_spi

risk_spi_cards: risk_spi_cards.c
	gcc risk_spi_cards.c -o risk_spi_cards

risk_spi_gamestate: risk_spi_gamestate.c
	gcc risk_spi_gamestate.c -o risk_spi_gamestate

risk_spi_stats: risk_spi_stats.c
	gcc risk_spi_stats.c -o risk_spi_stats
